### ISSUE TITLE
#21 test

### ISSUE THREAD

**Issue by ak0327** [minishellakirawchen/minishell_rev1#21]
* memory leakのチェックはleaks commandを使用
　* terminalを2つ開き、片方で以下コマンド、片方でminishellを起動
　* `while [ 1 ]; do leaks -q minishell; sleep 1; done`
~~* 1 leaks `export a b c=d e++ e+=1 a=hoge`
　* `expor e++`単体でリークを確認~~ -> 修正@https://github.com/minishellakirawchen/minishell_rev1/commit/d66cb6a7084986f53c6d1c897f99026fbed59db4

**Comment by ak0327** [comment]
* ~~unexpecter termination `echo hello && (cd /bin && ls && echo hello | echo world)
; cat Makefile >otufile`
　* `(cd)`でアウトの模様
　* `(env)`もアウト
　* `(echo)`もアウト
　* `(echo hello)`もできない
　* 数日前は動いていたはず。何か変更したっけ？~~

修正完了
* #19 で作業していたためそちらにpushしたhttps://github.com/minishellakirawchen/minishell_rev1/commit/6f815aa72c15b7aef403f152b47b30f27e396ba3
* return valueをFAILUREからPROCESS_ERRORに変更したことにより、subshellが正常に分岐できなくなっていた模様

**Comment by ak0327** [comment]
* PATHが見つからない時のコマンド実行関係の挙動は要確認
　* 現状は`.` or `/` で開始するファイルをpathとして認識し、exeveに渡しているがそれで良いか？ `./`の方が良さそう？`.`で始まるファイルに対応していない気がする

**Comment by ak0327** [comment]
* `unset PATH` -> `env` でcrash, minishellenvでvalue=NULLを考慮できていないからか？
* `unset PATH` -> `export`でcrash, `hoge`でもbuiltin/not は関係ない　minishellenvは修正ずみ
* 環境変数PATH=NULLでminishellを起動するとPATHを追加、unsetしたりしてもcrashしない

#22 へ移行

**Comment by weijuan82113** [comment]
memory leak問題を再度見直し、free関数を修正しました。
ご提示いただいたテスト項目はleakしなくなりました。
