### ISSUE TITLE
#22 unset

### ISSUE THREAD

**Issue by ak0327** [minishellakirawchen/minishell_rev1#22]
* `unset PATH` -> `env` でcrash, minishellenvでvalue=NULLを考慮できていないからか？
* `unset PATH` -> `export`でcrash, `hoge`でもbuiltin/not は関係ない　minishellenvは修正ずみ
* 環境変数PATH=NULLでminishellを起動するとPATHを追加、unsetしたりしてもcrashしない...(1)

<br>

* `unset PATH`するとenvlistのヌル判定をした瞬間にクラッシュする なんで？ 
* [@@ degug print]envlist]の後にsegv

```c
void	print_env(t_list *envlist)
{
	t_env_elem	*env_elem;

	printf("\n[@@ degug print]envlist\n");
	if (!envlist)
	{
		printf("(null)\n");
		return ;
	}
	while (envlist)
	{
		env_elem = envlist->content;
		if (!env_elem)
			printf("content: (null)\n");
		else
			printf("key: %s, value:%s\n", env_elem->key, env_elem->value);
		envlist = envlist->next;
	}
}
```

<br>

* envlist, elemのpointerは表示される　elemのkey, valueにアクセスした瞬間にクラッシュしているみたい

```c
void	debug_print_env(t_list *envlist)
{
	t_env_elem	*env_elem;

	printf("\n[@@ degug print]envlist\n");
	printf("envlist pointer:%p\n", envlist);
	if (!envlist)
	{
		printf("(null)\n");
		return ;
	}
	while (envlist)
	{
		env_elem = envlist->content;
		printf("envelem pointer:%p\n", env_elem);
		if (!env_elem)
			printf("content: (null)\n");
		else
			printf("key: %s, value:%s\n", env_elem->key, env_elem->value);
		envlist = envlist->next;
	}
}

```
<br>

* `unset PATH`の後に変なアドレス指してる。先頭のunsetが怪しい？
```shell
// before unset
[@@ degug print]envlist
envlist pointer:0x600003688040
envelem pointer:0x60000348d180
key: PATH, value:/Users .(略)

// after unset
[@@ degug print]envlist
envlist pointer:0x600003688040
envelem pointer:0x3d5287688040
zsh: segmentation fault  ./minishell

```
<br>

* envlistの先頭の要素をunsetするとcrashするみたい
　* ↑でやった(1)はPATHが先頭でないケース
　* exportで色々追加して、envの先頭をunsetするとクラッシュした 
* 末尾の要素のunsetは問題なし

**Comment by ak0327** [comment]
#21 から移行

**Comment by weijuan82113** [comment]
t_info->envlist_headのポインターをコピーしてからunsetしましたので、t_info->envlist_headがnullになってsegment faultになりました。t_info->envlist_headのポインターも新しnext nodeに変更するように修正しました
