### ISSUE TITLE
#23 Test

### ISSUE THREAD

**Issue by ak0327** [minishellakirawchen/minishell_rev1#23]

**Comment by ak0327** [comment]
```shell
 while [ 1 ]; do leaks -q minishell; sleep 1; done
```

**Comment by ak0327** [comment]
*~`cat | cat | ls` ができなくなっている~
  * ~関数分割の際に何かしたかも~
  * ~`cat | ls`  -> EOFでsegv~
  * ~`cat | echo << end` で `cat: stdin: Input/output error　Segmentation fault: 11`~
* ~hoge|hugaのようにパイプ連結時のpaesingがバグっている~
  * ~create command listでおかしくなってる~
  * ~分割後のバグ修正えぐい　はじめから行数考えるべきだった（考えていたはずなんだが）~


修正完了

**Comment by ak0327** [comment]
* `()`はNG, `(())`はOKらしい　なにこれ
  * ~これは保留~ -> ~やった @https://github.com/minishellakirawchen/minishell_rev1/commit/8115c4708f5dde2c3be67d93fdaf48730df220f7~ -> 削除した

**Comment by ak0327** [comment]
~* `minishell $> <<`~
  ~* minishell: syntax error near unexpected token `<<'~
  ~* bash: syntax error near unexpected token `newline'~

修正完了 @ #26  https://github.com/minishellakirawchen/minishell_rev1/commit/270358df8fd2b4eb6beb5c3e7b9ea7e9e626c99a

**Comment by ak0327** [comment]
* ~`space`x2以上の入力でleak~ inputのcontinueの際にclear inputを通すように変更

**Comment by ak0327** [comment]
~~* `export c=$PATH` -> minishell: export: `Support/(略) ': not a valid identifier~~
 ~~* PATHに`space`があると分解されて渡されているみたい？問題ないか見直す~~
以下にて解決

**Comment by ak0327** [comment]
~~* ` export a="hello   world"; export b=$a`の際、$a="hello", "world"で渡されるためb=hello, worldはerrorとなる。bashは$b="hello   world"として登録~~
~~* `echo $a`は`{"echo" "hello", "world"}`として振る舞っているのに...？assignmentで挙動が変わるのか？それはめんどい。保留~~
~~* ワイルドカードと同じように、exportの時にre tokenizeしないようにできそう~~

```shell
bash3.2_2[0] $ export a="hello        world"
bash3.2_2[0] $ export b=$a
bash3.2_2[0] $ export c="export d=$a"
bash3.2_2[0] $ echo $a  //hello world
bash3.2_2[0] $ echo $b  //hello world
bash3.2_2[0] $ echo $c  //export d=hello world
bash3.2_2[0] $ echo $d  //
bash3.2_2[0] $ $c
bash3.2_2[0] $ echo $c  //export d=hello world
bash3.2_2[0] $ echo $d  //hello  <- "hello"までしか登録されていない
```
~~* re tokenizeするときに先頭が`export`であればre tokenizeしなければよさそう~~
~~* これで $dの挙動も再現できる~~
~~* "export d=hello     world"のような塊で来た時には分割できる~~

対応完了！
heredocでも同様の展開になっていて。対応しておいてよかった。

**Comment by ak0327** [comment]
使用可能関数：問題なし（memcpyが呼ばれているが探せない。コンパイラの仕業？）

**Comment by ak0327** [comment]
```shell
minishell $> cat <<end; sleep 10 ; cat << end
> hoge
> end
> hoge
> end
hoge
hoge
unlink: No such file or directory

```

**Comment by ak0327** [comment]
> 

修正完了 @ #26

**Comment by ak0327** [comment]
> * `minishell $> <<`
>   
>   * minishell: syntax error near unexpected token `<<'
>   * bash: syntax error near unexpected token `newline'

修正完了 @ #26

**Comment by ak0327** [comment]
ここまでの変更分をmianへmerge

**Comment by ak0327** [comment]
* exit
```shell
bash-3.2-2 255 $ exit 1 | exit 2 | exit 3
bash-3.2-2 3 $ 
```
複数のケースで終了しない
exit出力しない

**Comment by ak0327** [comment]
* heredoc eof後に改行し出力される

**Comment by ak0327** [comment]
# Feb/6th test

##  exit
```shell
bash-3.2-2 255 $ exit 1 | exit 2 | exit 3
bash-3.2-2 3 $ 
```
複数のケースで終了しない
exit出力しない

##  heredoc
* eof後に改行し出力される

## quote expansion
  * quote expansionの挙動が異なる
```shell
bash-3.2-2 0 $ "$c"
bash: "echo    hello     world": command not found
bash-3.2-2 127 $ 
bash-3.2-2 127 $ 
bash-3.2-2 127 $ $c
bash: "echo: command not found
```

## export
  * `export +=test`でエラーが出ない
```shell
bash-3.2-2 0 $ export abc +=test
bash: export: `+=test': not a valid identifier
```

## cd
   * leaks
   * `cd PATH`遷移後の`cd -`で`OLDPWD=NULL`になる

**Comment by ak0327** [comment]
quote expasion, heredoc, exitは #28 で修正する -> 完了

**Comment by ak0327** [comment]
# Feb/7th test

## command execution
* `unset PATH` でのコマンド実行
*  minishellはcommand not found, bashはcurrentを実行
* current dirのlsはcatをcopyしてrenameした

```shell
bash3.2_3[0] $ unset PATH
bash3.2_3[0] $ ls in1
in1dayo
bash3.2_3[0] $ ./ls in1
in1dayo
bash3.2_3[0] $ /bin/ls
dir             dir2            in1             in3             ls              ou2             out2

minishell 0 $> unset PATH
minishell 0 $> ls in1
minishell: ls: command not found
minishell 127 $> ./ls in1
in1dayo
minishell 0 $> /bin/ls
dir             dir2            in1             in3             ls              ou2             out2

```

## exit
* `exit`引数なしはstatusを保持したままexitが正しい挙動
  * ex) syntaxerror 258 -> `exit`でstatusは2
  * ex)`^C` 1 -> `exit` でstatusは1

## cd
* `cd nothing` はstatusを1に変更する

**Comment by weijuan82113** [comment]
> # Feb/7th test
> ## command execution
> * `unset PATH` でのコマンド実行
> * minishellはcommand not found, bashはcurrentを実行
> * current dirのlsはcatをcopyしてrenameした
> 
> ```shell
> bash3.2_3[0] $ unset PATH
> bash3.2_3[0] $ ls in1
> in1dayo
> bash3.2_3[0] $ ./ls in1
> in1dayo
> bash3.2_3[0] $ /bin/ls
> dir             dir2            in1             in3             ls              ou2             out2
> 
> minishell 0 $> unset PATH
> minishell 0 $> ls in1
> minishell: ls: command not found
> minishell 127 $> ./ls in1
> in1dayo
> minishell 0 $> /bin/ls
> dir             dir2            in1             in3             ls              ou2             out2
> ```
> 
> ## exit
> * `exit`引数なしはstatusを保持したままexitが正しい挙動
>   
>   * ex) syntaxerror 258 -> `exit`でstatusは2
>   * ex)`^C` 1 -> `exit` でstatusは1

→修正修正済み
 
> ## cd
> * `cd nothing` はstatusを1に変更する

→修正修正済み

**Comment by weijuan82113** [comment]
> # Feb/6th test
> ## exit
> ```shell
> bash-3.2-2 255 $ exit 1 | exit 2 | exit 3
> bash-3.2-2 3 $ 
> ```
> 
> 複数のケースで終了しない exit出力しない
> 
> ## heredoc
> * eof後に改行し出力される
> 
> ## quote expansion
> * quote expansionの挙動が異なる
> 
> ```shell
> bash-3.2-2 0 $ "$c"
> bash: "echo    hello     world": command not found
> bash-3.2-2 127 $ 
> bash-3.2-2 127 $ 
> bash-3.2-2 127 $ $c
> bash: "echo: command not found
> ```
> 
> ## export
> * `export +=test`でエラーが出ない

→修正済み

> ```shell
> bash-3.2-2 0 $ export abc +=test
> bash: export: `+=test': not a valid identifier
> ```

→修正済み

> ## cd
> * leaks
> * `cd PATH`遷移後の`cd -`で`OLDPWD=NULL`になる

→修正済み

**Comment by ak0327** [comment]
# Feb/8th test
* 修正は ~(1)~ , ~(2)~ ,**(3)**, ~(4)~ , ~(5)~ , ~(6)~ くらい？ あとは余裕があればやる

## ~redirect & signal~ -> 完了？？ 取り掛かろうと思ったら再現できず。他の修正でいじった影響か？テスト前に環境に変なことしたかも？再発が怖い
* ~単独の`> out`ができなくなっている    .........................................**(1)**~
* ~単独の`>> out` これも同様~
* ~exit statusが想定していないsignalの分岐に入っている？~
```shell
// NG
minishell 1 $> >out
Interrupt by signal : 11

// これはOK
minishell 0 $> echo hello > out



// NG
minishell 0 $> <<end
> hoge
> end
Interrupt by signal : 11

// これはOK
minishell 0 $> cat <<end
> hoge
> end
hoge
minishell 0 $> 
```

<br>

## ~~&& ||~~ -> 完了 
* ~~複数段あるときの挙動が異なる   .........................................**(2)**~~
* ~~cmd1 &&/|| cmd2 だけで評価してるっぽい~~

```shell
bash3.2_2[0] $ echo 1 && echo 2 || echo 3 || echo 4 && echo 5
1
2
5

minishell 0 $> echo 1 && echo 2 || echo 3 || echo 4 && echo 5
1
2

```


<br>
<br>
<br>

以降、テストケース参考元
https://github.com/nafuka11/42_minishell_tester

<br>

## cd
* シンボリックリンク経由のcdでpwdが異なる .........................................**(3)**
```shell
echo $PWD, mkdir dir; ln -s dir symdir; cd symdir
```

<br>

## echo 
* OK

<br>

## ~exit~ -> 完了
* ~引数2つのケース ...............................................................................**(4)**~
```shell
minishell 0 $> exit -- 42
exit
minishell: exit: --: numeric argument required
minishell 255 $> 

bash3.2_4[0] $ exit -- 42
exit
bash3.2_3[42] $

<br>

```
*  ~符号のみ ...............................................................................**(5)**~ -> 完了
  * ~これはstrtolの修正~
```shell
minishell 0 $> exit +
exit
bash3.2_2[0] $ 

bash3.2_3[0] $ exit +
exit
bash: exit: +: numeric argument required
bash3.2_2[255] $ 
```

<br>

* ~`;`の入るケース~ -> 完了
```shell
minishell 0 $> exit 0 0; exit
exit
minishell: exit: too many arguments
exit
bash3.2_2[1] $ 

// exitしないらしい(shlvl=5のまま)
bash3.2_5[0] $ exit 0 0; exit
exit
bash: exit: too many arguments
bash3.2_5[1] $ 

```

<br>

## expand
* OK

<br>

## export 
* OK

<br>

## path
* OK

<br>

## pwd
* shell立ち上げてすぐの`$OLDPDW=NULL`
* テスト全てやっていないので他にもあるかも
```shell
takira % ./minishell 
minishell 0 $> echo $OLDPWD
/Users/akira/Documents/Programming/CLionProjects/42/42cursus/03_minishell_rev1
minishell 0 $> 

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash3.2_6[0] $ echo $OLDPWD

bash3.2_6[0] $
```

<br>


## redirect
* OK

<br>

## ~simple command~  -> 完了
* ~pathが見つからなかった時のエラーメッセージが異なる~
* ~pathでない場合には`command not found`, `.`始まりの場合には`no such file or directory`, `/`始まりの場合には`not a directory`になる~
```shell
minishell 0 $> no_such_file
minishell: no_such_file: command not found
minishell 127 $> ./no_such_file
minishell: ./no_such_file: command not found
minishell 127 $> /bin/ls/no_such_file
minishell: /bin/ls/no_such_file: command not found

bash3.2_6[0] $ no_such_file
bash: no_such_file: command not found
bash3.2_6[127] $ ./no_such_file
bash: ./no_such_file: No such file or directory
bash3.2_6[127] $ /bin/ls/no_such_file
bash: /bin/ls/no_such_file: Not a directory

```

<br>

* ~`$nothing`単独の場合はcommand not foundにしない ..................................**(6)**~ ->完了

```shell
minishell 127 $> echo a | $NO_ENV 
minishell: : command not found
minishell 127 $> 

bash3.2_6[1] $ echo a | $NO_ENV 
bash3.2_6[0] $ 
```


<br>

## ~syntax error~ -> 完了
~* エラー文が異なる~
```shell
// semicolon
minishell 258 $> ;;
minishell: syntax error near unexpected token `;;'
minishell 258 $> ;;;
minishell: syntax error near unexpected token `;;;'
minishell 258 $> ;;;;
minishell: syntax error near unexpected token `;;;;'

bash: syntax error near unexpected token `;;'
bash3.2_6[258] $ ;;;
bash: syntax error near unexpected token `;;'
bash3.2_6[258] $ ;;;;
bash: syntax error near unexpected token `;;'


// redirection >
minishell 258 $> >>>
minishell: syntax error near unexpected token `>>>'
minishell 258 $> >>>>
minishell: syntax error near unexpected token `>>>>'

bash3.2_6[258] $ >>>
bash: syntax error near unexpected token `>'
bash3.2_6[258] $ >>>>
bash: syntax error near unexpected token `>>'

// redirection < >
minishell 258 $> < >
minishell: syntax error near unexpected token `newline'

bash3.2_6[258] $ < >
bash: syntax error near unexpected token `>'


// redirection command  < >
minishell 258 $> cat < >
minishell: syntax error near unexpected token `newline'

bash3.2_6[258] $ cat < >
bash: syntax error near unexpected token `>'
bash3.2_6[258] $ 


```

<br>

## unset
* OK


<br>

**Comment by ak0327** [comment]
`(())`はsubshellではなく算術演算の展開らしい
対応する必要なさそう
`(())`はsyntax errorに戻す

**Comment by ak0327** [comment]
* ~heredoc入力中に高速で^D->抜ける~ OK

**Comment by ak0327** [comment]
* `env --`

**Comment by ak0327** [comment]
* `export --`

**Comment by ak0327** [comment]
* rm -rf dir -> cd ./ -> pwdで`./`付与しなくなっている？

**Comment by ak0327** [comment]
leaks `rm -rf dir -> cd ..`

**Comment by ak0327** [comment]
* ~command fileに権限ない場合のerror msg, exit no~ OK
```shell
bash3.2_5[0] $ ./ls
bash: ./ls: Permission denied
bash3.2_5[126] $ 

```

**Comment by ak0327** [comment]
`<in1 cat | >out1 <<a`
* bashとの差異はなく挙動はOK
* ~outは空, なんで？~
  * パイプの左はcatしていないからでした。

**Comment by ak0327** [comment]
# Feb/9th test

* コマンド実行時にopen Bad addressが出た -> とりあえず対応完了
  * `int set_tc_attr_in_execute(void)` のperror("open")が出力されていた
  *  ->  下記のようにsubshell内でpipe, and, orを多用したコマンドでしか出ないため、とりあえずコメントアウトで対応
```shell
minishell 0 $> echo 1 | echo 2 && echo 3 | (echo 4 | echo 5 && echo 6) && echo 7; echo 8
2
open: Bad address
5
6
7
8

```

<br>

* ~interrupt by signal~  -> とりあえず対応完了　分岐は維持したままerror msgのprintを削除した
``` shell
minishell 0 $> echo 0 && (echo 1 | echo 2 && echo 3) | echo 4 | echo 5
0
5
Interrupt by signal : 13
```

**Comment by ak0327** [comment]
## cd

* `chmod -r ngdir; cd ngdir`
  * statusが13になる (bashは0)
  * `int check_dir_exist(char *tdir, char *cmd, int print_flag)` のEACCESS 13っぽい
  * ~`errno=EACCESS`の時に`access(tdir, X_OK) == 0`ならば`EXIT_SUCCESS`の分岐を追加して解決~ 
    *  ↑はbashを評価していただけだった...未解決

* `mkdir dir; cd dir; chmod -x dir; cd ..` でもstatusが13になる（bashは0）
  * status以外は問題なし

<br>

* `chmod 000 ngdir; chmod +r ngdir; cd ngdir` 
  * 移動はしていないためpath移動の挙動はOK
  * statusを0->1, error msgがあった方が良いかも？

```shell
minishell 0 $> cd ngdir
minishell 0 $> 
minishell 0 $> pwd
/Users/akira/Documents/Programming/CLionProjects/42/42cursus/03_minishell_rev1/testdir

bash3.2_4[0] $ cd ngdir/
bash: cd: ngdir/: Permission denied
bash3.2_4[1] $ 

```

<br>

* `mkdir dir; cd dir; rm -rf dir; cd ..`
  * status、挙動はOK
  * error msgが表示されるが、これは不要かも？
    * `cd: error retrieving current directory: getcwd: cannot access parent directories: directories: No such file or directory `

**Comment by ak0327** [comment]
```shell
minishell 0 $> ls
dir__   dir__x  dir_r_  dir_rx
minishell 0 $> cd dir_r_
minishell 0 $> pwd
/Users/akira/Documents/Programming/CLionProjects/42/42cursus/03_minishell_rev1/dir
minishell 0 $> 

bash3.2_2[0] $ cd dir_r_
bash: cd: dir_r_: Permission denied
bash3.2_2[1] $ 


```
